package psklab1.persistence.mybatis;

import java.util.List;

import org.mybatis.cdi.Mapper;
import psklab1.entities.mybatis.Driver;

@Mapper
public interface DriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    int deleteByPrimaryKey(String pin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    int insert(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    Driver selectByPrimaryKey(String pin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    List<Driver> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    int updateByPrimaryKey(Driver record);

    List<Driver> selectByFK(String key);
}