package psklab1.persistence.mybatis;

import java.util.List;

import org.mybatis.cdi.Mapper;
import psklab1.entities.mybatis.TeamStage;

@Mapper
public interface TeamStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM_STAGE
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    int insert(TeamStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM_STAGE
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    List<TeamStage> selectAll();
}