package psklab1.entities.mybatis;

public class Stage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STAGE.ID
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STAGE.NAME
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STAGE.ID
     *
     * @return the value of PUBLIC.STAGE.ID
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STAGE.ID
     *
     * @param id the value for PUBLIC.STAGE.ID
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STAGE.NAME
     *
     * @return the value of PUBLIC.STAGE.NAME
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STAGE.NAME
     *
     * @param name the value for PUBLIC.STAGE.NAME
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}