package psklab1.entities.mybatis;

public class TeamStage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM_STAGE.TEAMS_ID
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    private Integer teamsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM_STAGE.STAGES_ID
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    private Integer stagesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM_STAGE.TEAMS_ID
     *
     * @return the value of PUBLIC.TEAM_STAGE.TEAMS_ID
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    public Integer getTeamsId() {
        return teamsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM_STAGE.TEAMS_ID
     *
     * @param teamsId the value for PUBLIC.TEAM_STAGE.TEAMS_ID
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    public void setTeamsId(Integer teamsId) {
        this.teamsId = teamsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM_STAGE.STAGES_ID
     *
     * @return the value of PUBLIC.TEAM_STAGE.STAGES_ID
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    public Integer getStagesId() {
        return stagesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM_STAGE.STAGES_ID
     *
     * @param stagesId the value for PUBLIC.TEAM_STAGE.STAGES_ID
     *
     * @mbg.generated Mon Apr 08 22:15:17 EEST 2019
     */
    public void setStagesId(Integer stagesId) {
        this.stagesId = stagesId;
    }
}